config/routes.rb
OoExperiment::Application.routes.draw do
  
  devise_for :users, :path => "users", :path_names => { 
    :sign_in => 'sign-in', 
    :sign_out => 'sign-out', 
    :password => 'pswd', 
    :confirmation => 'verify', 
    :unlock => 'unlock', 
    :registration => 'register', 
    :sign_up => 'sign-up' 
  }
  
  resources :servers do
    resources :tasks do
      resources :server_task_statuses
    end
  end

end

app/controllers/server_task_statuses_controller.rb
class ServerTaskStatusesController < ApplicationController
  
  def index
    @server = Server.find(params[:server_id])
    @task = Task.find(params[:task_id])
    @server_task_statuses = ServerTaskStatus.where('server_id' => @server.id, 'task_id' => @task.id).order("created_at desc").all
    respond_to do |format|
      format.html
      format.xml  { render :xml => @server_task_statuses }
    end
  end

  def show
    @server = Server.find(params[:server_id])
    @task = Task.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @task }
    end
  end

  def new
    @server = Server.find(params[:server_id])
    @task = Task.find(params[:task_id])
    @server_task_status = ServerTaskStatus.new(:server_id => @server.id, :task_id => @task.id)
    respond_to do |format|
      format.html
      format.xml  { render :xml => @server_task_status }
    end
  end

  def edit
    @server = Server.find(params[:id])
  end

  def create
    @server = Server.find(params[:server_id])
    @task = Task.find(params[:task_id])
    params[:server_task_status][:server_id] = @server.id;
    params[:server_task_status][:task_id] = @task.id;
    @server_task_status = ServerTaskStatus.new(params[:server_task_status])
    respond_to do |format|
      if @server_task_status.save
        format.html { redirect_to(server_task_server_task_statuses_path(@server, @task)) }
        format.xml  { render :xml => @server_task_status, :status => :created, :location => @server_task_status }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @server_task_status.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @server = Server.find(params[:id])

    respond_to do |format|
      if @server.update_attributes(params[:server])
        format.html { redirect_to(@server, :notice => 'Server was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @server.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @server = Server.find(params[:id])
    @server.destroy

    respond_to do |format|
      format.html { redirect_to(servers_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/server_task_statuses/_form.html.haml
= form_for [@server, @task, @server_task_status] do |f|

  %div{ "data-role" => "fieldcontain" }
    = f.label :status_id
    = select(:server_task_status, :status_id, ServerTaskStatus::STATUSES)

  %div{ "data-role" => "fieldcontain" }
    = f.label :remarks
    = f.text_area :remarks, :input_html => { :rows => 4 }

  = f.submit

app/views/server_task_statuses/index.html.haml
- @page_title = "Statuses for #{@server.name} task"
- @header_button_left = { :name => "Tasks for #{@server.name}", :icon => "arrow-l", :url => @server }
- @header_button_right = { :name => "Add new status", :icon => "new", :url => new_server_task_server_task_status_path(@server, @task) }
/= debug ActiveSupport::TimeZone.all.map(&:name)
- tz = "Singapore"
- current_date = Time.now.in_time_zone(tz).to_date
- new_day = true
- statuses = []
- ServerTaskStatus::STATUSES.collect { |a , b| statuses[b] = a }
%ul{"data-role" => "listview", "data-inset" => "true", "data-dividertheme" => "#{h jqmobile_theme('data-divider')}", "data-theme" => "#{h jqmobile_theme('data')}"}
  %li{"data-role" => "list-divider"}= current_date.strftime("%d %b %Y Today")
  - if @server_task_statuses.present?
    - @server_task_statuses.each do |server_task_status|
      - if server_task_status.created_at.in_time_zone(tz).to_date != current_date
        - date_diff = (current_date - server_task_status.created_at.in_time_zone(tz).to_date).to_i
        - (1..date_diff).each do |i|
          - current_date = current_date - 1
          %li{"data-role" => "list-divider"}= current_date.strftime("%d %b %Y %A")
        - new_day = true
      - if new_day
        - new_day = false
      %li
        %p.ui-li-aside 
          %strong= statuses[server_task_status.status_id]
        %h3= server_task_status.created_at.in_time_zone(tz)
        :markdown
          #{server_task_status.remarks}
  - else
    %li
      %h3 No status updates in the past 7 days.

app/views/server_task_statuses/new.html.haml
-	@page_title = "Update status"
- @header_button_left = { :name => "Back", :icon => "arrow-l", :url => servers_path }
= render 'form'