config/routes.rb
OoExperiment::Application.routes.draw do
  
  devise_for :users, :path => "users", :path_names => { 
    :sign_in => 'sign-in', 
    :sign_out => 'sign-out', 
    :password => 'pswd', 
    :confirmation => 'verify', 
    :unlock => 'unlock', 
    :registration => 'register', 
    :sign_up => 'sign-up' 
  }
  
  resources :servers do
    resources :tasks do
      resources :server_task_statuses
    end
  end

end

app/models/server.rb
class Server < ActiveRecord::Base
  validates :name, :uniqueness => { :scope => :server_type_id }, :presence => true, :length => { :within => 2..31 }
  validates :description, :length => { :maximum => 511 }
  validates :server_type_id, :presence => true, :numericality => true

  belongs_to :server_type
  has_many :server_task_statuses
end

app/models/server_type.rb
class ServerType < ActiveRecord::Base
  validates :name, :uniqueness => true, :presence => true, :length => { :within => 2..31 }
  validates :description, :length => { :maximum => 511 }

  has_many :servers
  has_many :categories
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController

  def index
    @servers = Server.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @servers }
    end
  end

  # GET /servers/1
  # GET /servers/1.xml
  def show
    @server = Server.find(params[:id])
    @server_type = ServerType.find(@server.server_type_id)
    @categories = Category.where({ :server_type_id => @server_type.id })

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @server }
    end
  end

  # GET /servers/new
  # GET /servers/new.xml
  def new
    @server = Server.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @server }
    end
  end

  # GET /servers/1/edit
  def edit
    @server = Server.find(params[:id])
  end

  # POST /servers
  # POST /servers.xml
  def create
    @server = Server.new(params[:server])

    respond_to do |format|
      if @server.save
        format.html { redirect_to(servers_path) }
        format.xml  { render :xml => @server, :status => :created, :location => @server }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @server.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /servers/1
  # PUT /servers/1.xml
  def update
    @server = Server.find(params[:id])

    respond_to do |format|
      if @server.update_attributes(params[:server])
        format.html { redirect_to(@server) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @server.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /servers/1
  # DELETE /servers/1.xml
  def destroy
    @server = Server.find(params[:id])
    @server.destroy

    respond_to do |format|
      format.html { redirect_to(servers_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/servers/_form.html.haml
= form_for @server do |f|

  %div{ "data-role" => "fieldcontain" }
    = f.label :name
    = f.text_field :name

  %div{ "data-role" => "fieldcontain" }
    = f.label :server_type_id
    = collection_select(:server, :server_type_id, ServerType.all, :id, :name)
    /=f.select :server_type_id

  %div{ "data-role" => "fieldcontain" }
    = f.label :description
    = f.text_area :description, :input_html => { :rows => 4 }

  = f.submit

app/views/servers/edit.html.haml
-	@page_title = "Editing #{@server.name}"
- @header_button_left = { :name => "Cancel", :icon => "arrow-l", :url => @server }
= render 'form'

app/views/servers/index.html.haml
- @page_title = "Servers"
- @header_button_right = { :name => "New", :icon => "new", :url => new_server_path }
%ul{"data-role" => "listview", "role" => "listbox", "data-dividertheme" => "#{h jqmobile_theme('data-divider')}", "data-theme" => "#{h jqmobile_theme('data')}"}
  %li{"data-role" => "list-divider"} All servers
  - @servers.each do |server|
    %li{"role" => "option"}= link_to server.name, server

= link_to 'New Server', new_server_path

app/views/servers/new.html.haml
-	@page_title = "Add new server"
- @header_button_left = { :name => "Back", :icon => "arrow-l", :url => servers_path }
- @header_button_right = { :name => "Delete2", :icon => "delete", :url => "index.html" }
= render 'form'

app/views/servers/show.html.haml
- @page_title = "Tasks for #{@server.name}"
- @header_button_left = { :name => "All servers", :icon => "arrow-l", :url => servers_path }
- @header_button_right = { :name => "Edit #{@server.name}", :icon => "gear", :url => edit_server_path(@server) }

%p= @server.description

- @categories.each do |category|
  %ul{"data-role" => "listview", "data-inset" => "true", "data-theme" => "#{h jqmobile_theme('data')}", "data-counttheme" => "#{h jqmobile_theme('data-count')}", "data-dividertheme" => "#{h jqmobile_theme('data-divider')}"}
    %li{"data-role" => "list-divider"}= category.name
    - category.tasks.each do |task|
      %li{"data-role" => "option"}= link_to task.name, server_task_server_task_statuses_path(@server, task)
      /%li{"data-role" => "option"}= link_to task.name, new_server_task_server_task_status_path(@server, task)